### ISSUE TITLE
Database-stats example on example hosted endpoints page not valid

### ISSUE THREAD

**Issue by Daniel-SchaeferJ** [fluree/developers-site#5]
**Describe the bug**
https://docs.flur.ee/api/1.0.0/downloaded-endpoints/downloaded-examples 
When on this page the database endpoint is not valid. When submitting a post request the server throws a 400 error invalid action.

**To Reproduce**
1. Go to https://docs.flur.ee/api/1.0.0/downloaded-endpoints/downloaded-examples 
2. /database-stats endpoint in an API request of choice like postman
Throws this error in any API tool that I use. 
![image](https://user-images.githubusercontent.com/46212174/140786796-c0cdaac0-48a7-4099-9ff5-4d3d420020c0.png)

**Expected behavior**
Should return a JSON object of ledger stats 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

 - Latest docker container 

POSSIBLE FIX

I noticed in another part of your documentation that the endpoint was ledger-stats which IS a valid endpoint and returns the expected behavior here. 

![image](https://user-images.githubusercontent.com/46212174/140787042-af2f443d-3619-4282-ace5-860621fdbe56.png)

**Comment by fdmmarshall** [comment]
Hi Daniel, thanks for the issue! You are correct, `database-stats` was changed to `ledger-stats` a few releases ago. I'll update the old and current docs to the actual name. Thanks again for helping us out.
